export interface ConfigValues {
    continue_virtual_money: number
    stamina_recovery_virtual_money: number
    stamina_recovery_seconds: number
    stamina_recovery_value: number
    max_stamina_overflow: number
    max_virtual_money: number
    max_mana: number
    max_star_crumb: number
    pool_exp_gain_value: number
    pool_exp_gain_seconds: number
    max_pool_exp: number
    max_display_pool_exp: number
    max_follows_count: number
    max_followers_count: number
    max_display_followers_count: number
    max_player_name_length: number
    max_player_comment_length: number
    overflow_exp_to_mana_conversion_rate: number
    reward_multiplier_by_boost_point: number
    common_reward_multiplier_by_multi_play_mode: number
    limit_payment_under_16: number
    limit_payment_16_19: number
    alert_payment: number
    level_correction_value_by_recommended_element: number
    level_correction_value_for_moderate_level_comparison: number
    unknown_loc2: number
    max_bond_token: number
    treasure_shop_item_number: number
    special_pack_shop_days_as_new: number
    support_url: string
    max_boss_boost_point: number
    max_display_boss_boost_point: number
    max_boost_point: number
    max_display_boost_point: number
    craft_point_item_id: number
    wildcard_once_character_ticket_item_id: number
    wildcard_ten_times_character_ticket_item_id: number
    wildcard_once_rare4_character_ticket_item_id: number
    wildcard_once_equipment_ticket_item_id: number
    wildcard_ten_times_equipment_ticket_item_id: number
    encyclopedia_point_item_id: number
    star_grain_item_id: number
    gacha_one_max_count: number
    gacha_ten_max_count: number
    growth_fund_unlock_chapter: number
    gacha_crazy_ten_max_count: number
    monthly_bonus_payment_total_requirement: number
    crazygacha_ten_times_character_ticket_id: number
    reward_multiplier_by_newbie: number
    newbie_rank: number
    newbie_days: number
}

